\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename cl-icalendar.info
@settitle cl-icalendar
@c %**end of header

@include version.texi

@ignore
@c ---------------
@deffn {Generic function} name arg1 arg2 ... @result{} result
@table @strong

@c Parameters and values
@item Arguments and values
@table @var
@item arg1
...
@item arg2
...
@item result
...
@end table

@c Description
@item Description
...
...

@c Exceptional situations
@item Exceptional situations
...

@c Examples
@item Examples
@lisp
...
@end lisp

@c Affected by
@item {Affected by}
@c ...

@c Side effects
@item {Side effects}
@c ...

@c See also
@item {See also}
@c ...

@c Notes
@item Notes
@c ...
@end table
@end deffn
@end ignore


@c Copy the type, variable and function indexes to the cp one.
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp

@copying
This is the @cite{Common Lisp iCalendar Library Reference} updated for
the version @cite{@value{VERSION}}.

Copyright @copyright{} 2010  Mario Castel@'an Castro

Copyright @copyright{} 2010  David V@'azquez P@'ua

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.

A copy of the license is also available from the Free Software
Foundation Web site at @url{http://www.gnu.org/licenses/fdl.html}.
@end quotation

The document was typeset with
@uref{http://www.texinfo.org/, GNU Texinfo}.

@end copying


@titlepage
@title Common Lisp iCalendar Library
@subtitle An implementation of the iCalendar specification
@subtitle for cl-icalendar version @value{VERSION}.
@author Mario Castel@'an Castro
@author David V@'azquez P@'ua
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top Common Lisp iCalendar Library Reference

@insertcopying
@end ifnottex

@c Generate the nodes for this menu with `C-c C-u C-m'.
@menu
* Introduction::                
* Overview::                    
* Data types::                  
* Components::                  
* High level abstractions::     
* Conditions and error handling::  
* GNU Free Documentation License::  
* Index::                       
@end menu

@c Update all node entries with `C-c C-u C-n'.
@c Insert new nodes with `C-c C-c n'.
@node Introduction
@chapter Introduction

@menu
* Instalation::                 
* Conventions::                 
@end menu

@node Instalation
@section Instalation

@node Conventions
@section Conventions

All examples in this document are meant to be evaluated globally, so
all the cl-icalendar exported symbols are accesible.

@node Grammar notation
@subsection Grammar notation

We use a modification of the BNF syntax, here called XBNF, wich is as
follows (In itself):

@verbatiminclude xbnf

@node Overview
@chapter Overview

@node Data types
@chapter Data types

@menu
* Boolean::                     
* Integer::                     
* Float::                       
* Text::                        
* Binary::                      
* URI::                         
* Cal-address::                 
* UTC-Offset::                  
* Date::                        
* Time::                        
* Datetime::                    
* Duration::                    
* Period::                      
* Recur::                       
@end menu

@deftp {Data type} icalendar-value-type
@end deftp

@c ---------------
@deffn {Generic function} parse-value string type @result{} object
This function parse the @var{string} acording to the symbol
@var{type}, if a symbol use it directly, if a string call lookup-type.
@end deffn

@deffn Function lookup-type string
When string is ``BOOLEAN'', ``CAL-ADDRE, ``DATE'', ``DATE-TIME,
``DURATION', ``FLOAT'', ``INTEGER'', ``PERIOD'', ``TIME'', ``URI'',
... convert it to a symbol with @code{intern}, else signal an error.

@c TODO: Add rest types
@end multitable
@end deffn

@node Boolean
@section Boolean

A value ethier nil for FALSE and t for TRUE

@node Integer
@section Integer

@deftypefun integer parse-value string (eq ``INTEGER'')
Parse a base-10 integer with the syntax

@end deftypefun

@node Float
@section Float

@deftypefun float parse-value string (eq ``FLOAT'')
Parse a float:

@end deftypefun

@node Text
@section Text

@deftypefn {Value Type} string parse-value string (eq ``TEXT''
This function 
@end deftypefn

@node Binary
@section Binary



@node URI
@section URI

@node Cal-address
@section Cal-address

@node UTC-Offset
@section UTC-Offset


@node Date
@section Date
@deffn Method parse-value string (eq ``DATE'')
Convert a string of the from YYYYMMDD to a @var{date} object.
@end deffn

@deftp {Value type} date day

A Date represent a range of 24 hours begining in hour 0, it is, a
``day'', ethier in the local timezone or in a defined timezone.

@defvr Slot day
An integer counting the days from or until if negative to
2000--03--01.
@end defvr

@defvr Slot timezone
A @var{timezone} or nil, if is a floating
@end defvr

@deffn Method date-year
Gives the year of the date, counting from 1 A.C.
@end deffn

@deffn Method date-month
Gives the month of the date, 1 for January --- 12 for December
@end deffn

@deffn Method date-day
Gives the day of month of the date, counting from 1
@end deffn

@end deftp

@node Time
@section Time

Time represent a offset from the begin of a day in UTC or in the local
timezone, 2 separate types are used:

Class: @var{floating-time} hours seconds

Represent a time wich is not timezone bind,

Class @var{absolute-time} seconds

Is a time always bound to UTC.

Method: 

@node Datetime
@section Datetime

Datetime is a absolute point in time.

@deftp {Value type} datetime day seconds subsecond

@defvr Slot day
is an integer counting the days from or until if negative to
2000--03--01, as in @var{date} type.
@end defvr

@defvr Slot seconds
Is the offset in SI seconds from 00:00:00 of the day.
@end defvr

@defvr Slot subsecond
Is a rational 0 <= @var{subsecond} < 1 representing
the sub-second offset from the begin of the @var{second}.
@end defvr

@end deftp

@node Duration
@section Duration

@node Period
@section Period

@node Recur
@section Recur

@node Components
@chapter Components

@node High level abstractions
@chapter High level abstractions

@node Conditions and error handling
@appendix Conditions and error handling@*

@node GNU Free Documentation License
@appendix GNU Free Documentation License
@c Get fdl.texi from http://www.gnu.org/licenses/fdl.html
@include fdl.texi

@node Index
@unnumbered Index
@printindex cp

@bye

@c cl-icalendar.texi ends here
